<a href="https://colab.research.google.com/github/sajjkavinda/ML-based-Intrution-detection-system/blob/main/Data_Inspection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing


**Title:**
ML-Based Intrution Detection System for SMBs

Dataset: CSE-CIC-IDS2018

This notebook performs the complete preprocessing pipeline used in this research before feature engineering and model training.

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Import libraries

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

import warnings
warnings.filterwarnings("ignore")

# Display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

Set dataset and output paths

In [7]:
# Google Drive location

PROJECT_DIR = Path("/content/drive/MyDrive/MSc_Dissertation")

DATASET_DIR = PROJECT_DIR / "Dataset"

OUTPUT_DIR = DATASET_DIR / "Processed"

OUTPUT_DIR.mkdir(exist_ok=True)

DATA_FILE = DATASET_DIR / "Friday-16-02-2018_TrafficForML_CICFlowMeter.csv"

Load the dataset

In [8]:
df = pd.read_csv(DATA_FILE, low_memory=False)

print("Dataset loaded successfully.")

Dataset loaded successfully.

Initial dataset inspection

In [9]:
print("="*60)

print("Dataset Shape")
print(df.shape)

print("="*60)

print("Column Count")
print(len(df.columns))

print("="*60)

print("Data Types")
print(df.dtypes.value_counts())

print("="*60)

print("Memory Usage")

memory = df.memory_usage(deep=True).sum() / 1024**2

print(f"{memory:.2f} MB")

============================================================
Dataset Shape
(1048575, 80)
============================================================
Column Count
80
============================================================
Data Types
object    80
Name: count, dtype: int64
============================================================
Memory Usage
4158.26 MB

Preview dataset and information

In [10]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 80 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Dst Port           1048575 non-null  object
 1   Protocol           1048575 non-null  object
 2   Timestamp          1048575 non-null  object
 3   Flow Duration      1048575 non-null  object
 4   Tot Fwd Pkts       1048575 non-null  object
 5   Tot Bwd Pkts       1048575 non-null  object
 6   TotLen Fwd Pkts    1048575 non-null  object
 7   TotLen Bwd Pkts    1048575 non-null  object
 8   Fwd Pkt Len Max    1048575 non-null  object
 9   Fwd Pkt Len Min    1048575 non-null  object
 10  Fwd Pkt Len Mean   1048575 non-null  object
 11  Fwd Pkt Len Std    1048575 non-null  object
 12  Bwd Pkt Len Max    1048575 non-null  object
 13  Bwd Pkt Len Min    1048575 non-null  object
 14  Bwd Pkt Len Mean   1048575 non-null  object
 15  Bwd Pkt Len Std    1048575 non-null  object
 16  Flow Byts/s        1048575 non-null  object
 17  Flow Pkts/s        1048575 non-null  object
 18  Flow IAT Mean      1048575 non-null  object
 19  Flow IAT Std       1048575 non-null  object
 20  Flow IAT Max       1048575 non-null  object
 21  Flow IAT Min       1048575 non-null  object
 22  Fwd IAT Tot        1048575 non-null  object
 23  Fwd IAT Mean       1048575 non-null  object
 24  Fwd IAT Std        1048575 non-null  object
 25  Fwd IAT Max        1048575 non-null  object
 26  Fwd IAT Min        1048575 non-null  object
 27  Bwd IAT Tot        1048575 non-null  object
 28  Bwd IAT Mean       1048575 non-null  object
 29  Bwd IAT Std        1048575 non-null  object
 30  Bwd IAT Max        1048575 non-null  object
 31  Bwd IAT Min        1048575 non-null  object
 32  Fwd PSH Flags      1048575 non-null  object
 33  Bwd PSH Flags      1048575 non-null  object
 34  Fwd URG Flags      1048575 non-null  object
 35  Bwd URG Flags      1048575 non-null  object
 36  Fwd Header Len     1048575 non-null  object
 37  Bwd Header Len     1048575 non-null  object
 38  Fwd Pkts/s         1048575 non-null  object
 39  Bwd Pkts/s         1048575 non-null  object
 40  Pkt Len Min        1048575 non-null  object
 41  Pkt Len Max        1048575 non-null  object
 42  Pkt Len Mean       1048575 non-null  object
 43  Pkt Len Std        1048575 non-null  object
 44  Pkt Len Var        1048575 non-null  object
 45  FIN Flag Cnt       1048575 non-null  object
 46  SYN Flag Cnt       1048575 non-null  object
 47  RST Flag Cnt       1048575 non-null  object
 48  PSH Flag Cnt       1048575 non-null  object
 49  ACK Flag Cnt       1048575 non-null  object
 50  URG Flag Cnt       1048575 non-null  object
 51  CWE Flag Count     1048575 non-null  object
 52  ECE Flag Cnt       1048575 non-null  object
 53  Down/Up Ratio      1048575 non-null  object
 54  Pkt Size Avg       1048575 non-null  object
 55  Fwd Seg Size Avg   1048575 non-null  object
 56  Bwd Seg Size Avg   1048575 non-null  object
 57  Fwd Byts/b Avg     1048575 non-null  object
 58  Fwd Pkts/b Avg     1048575 non-null  object
 59  Fwd Blk Rate Avg   1048575 non-null  object
 60  Bwd Byts/b Avg     1048575 non-null  object
 61  Bwd Pkts/b Avg     1048575 non-null  object
 62  Bwd Blk Rate Avg   1048575 non-null  object
 63  Subflow Fwd Pkts   1048575 non-null  object
 64  Subflow Fwd Byts   1048575 non-null  object
 65  Subflow Bwd Pkts   1048575 non-null  object
 66  Subflow Bwd Byts   1048575 non-null  object
 67  Init Fwd Win Byts  1048575 non-null  object
 68  Init Bwd Win Byts  1048575 non-null  object
 69  Fwd Act Data Pkts  1048575 non-null  object
 70  Fwd Seg Size Min   1048575 non-null  object
 71  Active Mean        1048575 non-null  object
 72  Active Std         1048575 non-null  object
 73  Active Max         1048575 non-null  object
 74  Active Min         1048575 non-null  object
 75  Idle Mean          1048575 non-null  object
 76  Idle Std           1048575 non-null  object
 77  Idle Max           1048575 non-null  object
 78  Idle Min           1048575 non-null  object
 79  Label              1048575 non-null  object
dtypes: object(80)
memory usage: 640.0+ MB

Class distribution

In [11]:
print(df["Label"].value_counts())

print()

print(df["Label"].value_counts(normalize=True) * 100)

Label
DoS attacks-Hulk            461912
Benign                      446772
DoS attacks-SlowHTTPTest    139890
Label                            1
Name: count, dtype: int64

Label
DoS attacks-Hulk            44.051403
Benign                      42.607539
DoS attacks-SlowHTTPTest    13.340963
Label                        0.000095
Name: proportion, dtype: float64

Missing values

In [12]:
missing = df.isnull().sum()

missing = missing[missing > 0]

print("Missing columns:")

display(missing)

Missing columns:

Series([], dtype: int64)

Duplicate values

In [13]:
duplicates = df.duplicated().sum()

print(f"Duplicate rows: {duplicates}")

Duplicate rows: 147586

Infinite values

In [14]:
numeric_df = df.select_dtypes(include=[np.number])

print("Infinite values:")

print(np.isinf(numeric_df).sum().sum())

Infinite values:
0.0

Summary of the inspection

In [15]:
df.describe(include="all")

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
count,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575
unique,14137,4,3178,453353,25,22,461,697,165,4,910,949,158,4,1444,1222,466688,489767,481581,495186,407844,58970,444141,453576,483854,413424,60166,201722,216407,237286,185326,39098,3,2,2,2,55,55,470701,406252,3,20,2005,2095,2095,3,3,3,3,3,3,2,3,6,1999,910,1444,2,2,2,2,2,2,25,461,22,697,25,23,16,6,5684,17,5685,5684,45989,100,45989,45989,4
top,80,6,16/02/2018 01:45:28,2,5,0,0,0,0,0,0,0,0,0,0,0,0,1000000,2,0,2,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,168,0,500000,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,225,-1,0,32,0,0,0,0,0,0,0,0,DoS attacks-Hulk
freq,461925,1048397,8403,62026,426705,438330,580627,580671,580627,1048552,580627,580642,580671,1048557,580671,580688,580625,62026,62026,516520,62026,112726,142344,142344,518949,142344,142344,578262,578262,579861,578262,578262,1048522,1048574,1048574,1048574,426262,438330,62037,438330,1048559,580625,580625,580625,580625,1047307,1048522,1048571,894425,892981,1022172,1048574,1048571,848124,580625,580627,580671,1048574,1048574,1048574,1048574,1048574,1048574,426705,580627,438330,580671,446529,438345,580676,906232,1039504,1048556,1039504,1039504,990321,1048394,990321,990321,461912

In [16]:
summary = {
    "Rows": len(df),
    "Columns": len(df.columns),
    "Duplicates": duplicates,
    "Missing Values": int(df.isnull().sum().sum()),
    "Memory(MB)": round(memory,2)
}

summary

{'Rows': 1048575,
 'Columns': 80,
 'Duplicates': np.int64(147586),
 'Missing Values': 0,
 'Memory(MB)': np.float64(4158.26)}