<a href="https://colab.research.google.com/github/sajjkavinda/ML-based-Intrution-detection-system/blob/main/Dataset_Inspection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!mkdir -p "/content/drive/MyDrive/MSc_Dissertation/Dataset"

In [4]:
!pip install awscli

Collecting awscli
  Downloading awscli-1.45.53-py3-none-any.whl.metadata (11 kB)
Collecting botocore==1.43.53 (from awscli)
  Downloading botocore-1.43.53-py3-none-any.whl.metadata (5.6 kB)
Collecting docutils<=0.19,>=0.18.1 (from awscli)
  Downloading docutils-0.19-py3-none-any.whl.metadata (2.7 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from awscli)
  Downloading s3transfer-0.19.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: PyYAML<6.1,>=3.10 in /usr/local/lib/python3.12/dist-packages (from awscli) (6.0.3)
Collecting colorama<0.4.7,>=0.2.5 (from awscli)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting rsa<4.8,>=3.1.2 (from awscli)
  Downloading rsa-4.7.2-py3-none-any.whl.metadata (3.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from botocore==1.43.53->awscli)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore==1.43.53->awscli) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore==1.43.53->awscli) (2.5.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from rsa<4.8,>=3.1.2->awscli) (0.6.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.43.53->awscli) (1.17.0)
Downloading awscli-1.45.53-py3-none-any.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 59.7 MB/s eta 0:00:00
Downloading botocore-1.43.53-py3-none-any.whl (15.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 75.3 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading docutils-0.19-py3-none-any.whl (570 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 30.3 MB/s eta 0:00:00
Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Downloading s3transfer-0.19.1-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.1/90.1 kB 5.4 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: rsa, jmespath, docutils, colorama, botocore, s3transfer, awscli
  Attempting uninstall: rsa
    Found existing installation: rsa 4.9.1
    Uninstalling rsa-4.9.1:
      Successfully uninstalled rsa-4.9.1
  Attempting uninstall: docutils
    Found existing installation: docutils 0.21.2
    Uninstalling docutils-0.21.2:
      Successfully uninstalled docutils-0.21.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 8.2.3 requires docutils<0.22,>=0.20, but you have docutils 0.19 which is incompatible.
Successfully installed awscli-1.45.53 botocore-1.43.53 colorama-0.4.6 docutils-0.19 jmespath-1.1.0 rsa-4.7.2 s3transfer-0.19.1

In [5]:
!aws s3 ls s3://cse-cic-ids2018/ \
    --no-sign-request

                           PRE Original Network Traffic and Log data/
                           PRE Processed Traffic Data for ML Algorithms/

In [6]:
!aws s3 ls "s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/" \
    --recursive \
    --no-sign-request

2018-10-11 16:02:25          0 Processed Traffic Data for ML Algorithms/
2018-10-11 16:02:49  352368373 Processed Traffic Data for ML Algorithms/Friday-02-03-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:03:10  333723605 Processed Traffic Data for ML Algorithms/Friday-16-02-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:03:33  382840456 Processed Traffic Data for ML Algorithms/Friday-23-02-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:03:59 4054925350 Processed Traffic Data for ML Algorithms/Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:08:38  107842858 Processed Traffic Data for ML Algorithms/Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:08:48  375945899 Processed Traffic Data for ML Algorithms/Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:09:20  382636202 Processed Traffic Data for ML Algorithms/Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:09:44  358223333 Processed Traffic Data for ML Algorithms/Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:10:12  328893673 Processed Traffic Data for ML Algorithms/Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv
2018-10-11 16:10:33  209249758 Processed Traffic Data for ML Algorithms/Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv

In [7]:
!aws s3 cp \
"s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Friday-16-02-2018_TrafficForML_CICFlowMeter.csv" \
"/content/drive/MyDrive/MSc_Dissertation/Dataset/" \
--no-sign-request

download: s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Friday-16-02-2018_TrafficForML_CICFlowMeter.csv to drive/MyDrive/MSc_Dissertation/Dataset/Friday-16-02-2018_TrafficForML_CICFlowMeter.csv

In [8]:
!aws s3 cp \
"s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv" \
"/content/drive/MyDrive/MSc_Dissertation/Dataset/" \
--no-sign-request

download: s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv to drive/MyDrive/MSc_Dissertation/Dataset/Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv

In [9]:
!aws s3 cp \
"s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv" \
"/content/drive/MyDrive/MSc_Dissertation/Dataset/" \
--no-sign-request

download: s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv to drive/MyDrive/MSc_Dissertation/Dataset/Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv

In [10]:
!aws s3 cp \
"s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Friday-23-02-2018_TrafficForML_CICFlowMeter.csv" \
"/content/drive/MyDrive/MSc_Dissertation/Dataset/" \
--no-sign-request

download: s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Friday-23-02-2018_TrafficForML_CICFlowMeter.csv to drive/MyDrive/MSc_Dissertation/Dataset/Friday-23-02-2018_TrafficForML_CICFlowMeter.csv

In [11]:
!aws s3 cp \
"s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv" \
"/content/drive/MyDrive/MSc_Dissertation/Dataset/" \
--no-sign-request

download: s3://cse-cic-ids2018/Processed Traffic Data for ML Algorithms/Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv to drive/MyDrive/MSc_Dissertation/Dataset/Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv

In [12]:
import pandas as pd
import numpy as np
import os

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [13]:
dataset_path = "/content/drive/MyDrive/MSc_Dissertation/Dataset"

files = sorted(os.listdir(dataset_path))

print(files)

['Friday-16-02-2018_TrafficForML_CICFlowMeter.csv', 'Friday-23-02-2018_TrafficForML_CICFlowMeter.csv', 'Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv', 'Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv', 'Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv']

In [14]:
df = pd.read_csv(
    "/content/drive/MyDrive/MSc_Dissertation/Dataset/Friday-16-02-2018_TrafficForML_CICFlowMeter.csv"
)

/tmp/ipykernel_1331/4264187998.py:1: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [15]:
print(df.shape)

df.head()

(1048575, 80)

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,16/02/2018 08:27:23,112640768,3,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.026633,56300000.0,138.592929,56300000,56300000,113000000,56300000.0,138.592929,56300000,56300000,0,0.0,0.0,0,0,0,0,0,0,0,0,0.026633,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,3,0,0,0,-1,-1,0,0,0,0.0,0,0,56300000.0,138.592929,56300000,56300000,Benign
1,0,0,16/02/2018 08:30:12,112641773,3,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.026633,56300000.0,263.750829,56300000,56300000,113000000,56300000.0,263.750829,56300000,56300000,0,0.0,0.0,0,0,0,0,0,0,0,0,0.026633,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,3,0,0,0,-1,-1,0,0,0,0.0,0,0,56300000.0,263.750829,56300000,56300000,Benign
2,35605,6,16/02/2018 08:26:55,20784143,23,44,2416,1344,240,64,105.043478,54.542292,64,0,30.545455,32.336497,180.907146,3.223611,314911.2576,1145953.758,9058214,66,20700000,940484.2727,1898330.299,9144734,66,20700000,482352.2093,1396411.114,9058214,41601,1,0,0,0,460,880,1.106613,2.116999,0,240,56.235294,53.851681,2900.003512,0,1,0,0,1,0,0,0,1,57.074627,105.043478,30.545455,0,0,0,0,0,0,23,2416,44,1344,263,255,22,20,2624734,0.0,2624734,2624734,9058214.0,0.0,9058214,9058214,Benign
3,0,0,16/02/2018 08:33:01,112640836,3,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.026633,56300000.0,82.024387,56300000,56300000,113000000,56300000.0,82.024387,56300000,56300000,0,0.0,0.0,0,0,0,0,0,0,0,0,0.026633,0.0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,3,0,0,0,-1,-1,0,0,0,0.0,0,0,56300000.0,82.024387,56300000,56300000,Benign
4,23,6,16/02/2018 08:27:59,20,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,100000.0,20.0,0.0,20,20,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,50000.0,50000.0,0,0,0.0,0.0,0.0,0,0,0,1,0,0,0,0,1,0.0,0.0,0.0,0,0,0,0,0,0,1,0,1,0,58856,0,0,20,0,0.0,0,0,0.0,0.0,0,0,Benign

In [16]:
df.columns.tolist()

['Dst Port',
 'Protocol',
 'Timestamp',
 'Flow Duration',
 'Tot Fwd Pkts',
 'Tot Bwd Pkts',
 'TotLen Fwd Pkts',
 'TotLen Bwd Pkts',
 'Fwd Pkt Len Max',
 'Fwd Pkt Len Min',
 'Fwd Pkt Len Mean',
 'Fwd Pkt Len Std',
 'Bwd Pkt Len Max',
 'Bwd Pkt Len Min',
 'Bwd Pkt Len Mean',
 'Bwd Pkt Len Std',
 'Flow Byts/s',
 'Flow Pkts/s',
 'Flow IAT Mean',
 'Flow IAT Std',
 'Flow IAT Max',
 'Flow IAT Min',
 'Fwd IAT Tot',
 'Fwd IAT Mean',
 'Fwd IAT Std',
 'Fwd IAT Max',
 'Fwd IAT Min',
 'Bwd IAT Tot',
 'Bwd IAT Mean',
 'Bwd IAT Std',
 'Bwd IAT Max',
 'Bwd IAT Min',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'Fwd Header Len',
 'Bwd Header Len',
 'Fwd Pkts/s',
 'Bwd Pkts/s',
 'Pkt Len Min',
 'Pkt Len Max',
 'Pkt Len Mean',
 'Pkt Len Std',
 'Pkt Len Var',
 'FIN Flag Cnt',
 'SYN Flag Cnt',
 'RST Flag Cnt',
 'PSH Flag Cnt',
 'ACK Flag Cnt',
 'URG Flag Cnt',
 'CWE Flag Count',
 'ECE Flag Cnt',
 'Down/Up Ratio',
 'Pkt Size Avg',
 'Fwd Seg Size Avg',
 'Bwd Seg Size Avg',
 'Fwd Byts/b Avg',
 'Fwd Pkts/b Avg',
 'Fwd Blk Rate Avg',
 'Bwd Byts/b Avg',
 'Bwd Pkts/b Avg',
 'Bwd Blk Rate Avg',
 'Subflow Fwd Pkts',
 'Subflow Fwd Byts',
 'Subflow Bwd Pkts',
 'Subflow Bwd Byts',
 'Init Fwd Win Byts',
 'Init Bwd Win Byts',
 'Fwd Act Data Pkts',
 'Fwd Seg Size Min',
 'Active Mean',
 'Active Std',
 'Active Max',
 'Active Min',
 'Idle Mean',
 'Idle Std',
 'Idle Max',
 'Idle Min',
 'Label']

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 80 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Dst Port           1048575 non-null  object
 1   Protocol           1048575 non-null  object
 2   Timestamp          1048575 non-null  object
 3   Flow Duration      1048575 non-null  object
 4   Tot Fwd Pkts       1048575 non-null  object
 5   Tot Bwd Pkts       1048575 non-null  object
 6   TotLen Fwd Pkts    1048575 non-null  object
 7   TotLen Bwd Pkts    1048575 non-null  object
 8   Fwd Pkt Len Max    1048575 non-null  object
 9   Fwd Pkt Len Min    1048575 non-null  object
 10  Fwd Pkt Len Mean   1048575 non-null  object
 11  Fwd Pkt Len Std    1048575 non-null  object
 12  Bwd Pkt Len Max    1048575 non-null  object
 13  Bwd Pkt Len Min    1048575 non-null  object
 14  Bwd Pkt Len Mean   1048575 non-null  object
 15  Bwd Pkt Len Std    1048575 non-null  object
 16  Flow Byts/s        1048575 non-null  object
 17  Flow Pkts/s        1048575 non-null  object
 18  Flow IAT Mean      1048575 non-null  object
 19  Flow IAT Std       1048575 non-null  object
 20  Flow IAT Max       1048575 non-null  object
 21  Flow IAT Min       1048575 non-null  object
 22  Fwd IAT Tot        1048575 non-null  object
 23  Fwd IAT Mean       1048575 non-null  object
 24  Fwd IAT Std        1048575 non-null  object
 25  Fwd IAT Max        1048575 non-null  object
 26  Fwd IAT Min        1048575 non-null  object
 27  Bwd IAT Tot        1048575 non-null  object
 28  Bwd IAT Mean       1048575 non-null  object
 29  Bwd IAT Std        1048575 non-null  object
 30  Bwd IAT Max        1048575 non-null  object
 31  Bwd IAT Min        1048575 non-null  object
 32  Fwd PSH Flags      1048575 non-null  object
 33  Bwd PSH Flags      1048575 non-null  object
 34  Fwd URG Flags      1048575 non-null  object
 35  Bwd URG Flags      1048575 non-null  object
 36  Fwd Header Len     1048575 non-null  object
 37  Bwd Header Len     1048575 non-null  object
 38  Fwd Pkts/s         1048575 non-null  object
 39  Bwd Pkts/s         1048575 non-null  object
 40  Pkt Len Min        1048575 non-null  object
 41  Pkt Len Max        1048575 non-null  object
 42  Pkt Len Mean       1048575 non-null  object
 43  Pkt Len Std        1048575 non-null  object
 44  Pkt Len Var        1048575 non-null  object
 45  FIN Flag Cnt       1048575 non-null  object
 46  SYN Flag Cnt       1048575 non-null  object
 47  RST Flag Cnt       1048575 non-null  object
 48  PSH Flag Cnt       1048575 non-null  object
 49  ACK Flag Cnt       1048575 non-null  object
 50  URG Flag Cnt       1048575 non-null  object
 51  CWE Flag Count     1048575 non-null  object
 52  ECE Flag Cnt       1048575 non-null  object
 53  Down/Up Ratio      1048575 non-null  object
 54  Pkt Size Avg       1048575 non-null  object
 55  Fwd Seg Size Avg   1048575 non-null  object
 56  Bwd Seg Size Avg   1048575 non-null  object
 57  Fwd Byts/b Avg     1048575 non-null  object
 58  Fwd Pkts/b Avg     1048575 non-null  object
 59  Fwd Blk Rate Avg   1048575 non-null  object
 60  Bwd Byts/b Avg     1048575 non-null  object
 61  Bwd Pkts/b Avg     1048575 non-null  object
 62  Bwd Blk Rate Avg   1048575 non-null  object
 63  Subflow Fwd Pkts   1048575 non-null  object
 64  Subflow Fwd Byts   1048575 non-null  object
 65  Subflow Bwd Pkts   1048575 non-null  object
 66  Subflow Bwd Byts   1048575 non-null  object
 67  Init Fwd Win Byts  1048575 non-null  object
 68  Init Bwd Win Byts  1048575 non-null  object
 69  Fwd Act Data Pkts  1048575 non-null  object
 70  Fwd Seg Size Min   1048575 non-null  object
 71  Active Mean        1048575 non-null  object
 72  Active Std         1048575 non-null  object
 73  Active Max         1048575 non-null  object
 74  Active Min         1048575 non-null  object
 75  Idle Mean          1048575 non-null  object
 76  Idle Std           1048575 non-null  object
 77  Idle Max           1048575 non-null  object
 78  Idle Min           1048575 non-null  object
 79  Label              1048575 non-null  object
dtypes: object(80)
memory usage: 640.0+ MB

In [18]:
df.describe()

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Tot,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Len,Bwd Header Len,Fwd Pkts/s,Bwd Pkts/s,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,Pkt Len Var,FIN Flag Cnt,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt,Down/Up Ratio,Pkt Size Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,Fwd Byts/b Avg,Fwd Pkts/b Avg,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
count,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575.0,1048575.0,1048575,1048575,1048575.0,1048575.0,1048575.0,1048575.0,1048575.0,1048575.0,1048575,1048575,1048575,1048575.0,1048575.0,1048575,1048575,1048575,1048575.0,1048575.0,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575.0,1048575.0,1048575,1048575,1048575.0,1048575.0,1048575.0,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575.0,1048575.0,1048575.0,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575.0,1048575,1048575,1048575.0,1048575.0,1048575,1048575,1048575
unique,14464,7,3178,453876,43,37,481,862,182,7,936.0,974.0,269,6,1629.0,1355.0,466738.0,490239.0,482016.0,495263.0,408374,59293,444573,453999.0,483928.0,413892,60511,201982,216668.0,237517.0,185603,39421,5,3,3,3,80,76,471211.0,406414.0,5,35,2199.0,2289.0,2289.0,4,5,5,5,5,5,3,5,10,2192.0,936.0,1629.0,3,3,3,3,3,3,43,481,37,862,42,37,25,11,5696,19.0,5697,5696,46002.0,138.0,46002,46002,4
top,80,6,16/02/2018 01:45:28,2,5,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,1000000.0,2.0,0.0,2,6,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,168,0,500000.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,5,0,0,0,225,-1,0,32,0,0.0,0,0,0.0,0.0,0,0,DoS attacks-Hulk
freq,461655,1040250,8403,58706,426407,438014,572790,572823,572790,1040366,572790.0,572802.0,572823,1040369,572823.0,572837.0,572788.0,58706.0,58706.0,508718.0,58706,112557,134812,134812.0,511139.0,134812,134812,570418,570418.0,572016.0,570418,570418,1040345,1040383,1040383,1040383,425965,438014,58717.0,438014.0,1040371,572788,572788.0,572788.0,572788.0,1039116,1040345,1040381,893790,892390,1013987,1040383,1040381,847479,572788.0,572790.0,572823.0,1040383,1040383,1040383,1040383,1040383,1040383,426407,572790,438014,572823,446265,438026,572826,905621,1031324,1040366.0,1031324,1031324,982182.0,1040244.0,982182,982182,461912

In [19]:
missing = df.isnull().sum()

missing = missing[missing > 0]

missing.sort_values(ascending=False)

Series([], dtype: int64)

In [20]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 145847

In [21]:
df["Label"].value_counts()

Label
DoS attacks-Hulk            461912
Benign                      446772
DoS attacks-SlowHTTPTest    139890
Label                            1
Name: count, dtype: int64

In [22]:
(
    df["Label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Label
DoS attacks-Hulk            44.05
Benign                      42.61
DoS attacks-SlowHTTPTest    13.34
Label                        0.00
Name: proportion, dtype: float64

In [23]:
np.isinf(df.select_dtypes(include=np.number)).sum().sum()

np.float64(0.0)

In [24]:
df.dtypes.value_counts()

object    80
Name: count, dtype: int64